name: sparkflow
version: 0.6.6
author: Alexander Ewetumo <trinoxf@gmail.com>
description: A flow-based approach to app development using a simple expressive approach
homepage: http://github.com/influx6/sparkflow.dart
dependencies:
  ds: any
  hub: any
  streamable: any
