name: sparkflow
author: Alexander Ewetumo<trinoxf@gmail.com>
version: 0.1.0
homepage: http://github.com/influx6/sparkflow.dart
description: A flow-based approach to app development using a simple expressive approach
dependencies:
  browser: any
  ds: any
  guardedfs: any
  hub: any
  streamable: any
